version: '3.3'
networks:
  ddcc-net:
    name: ddcc-net

volumes:
  hapi-postgres:

services:
  db:
    container_name: hapi-postgres
    image: postgres:11-alpine
    networks:
      - ddcc-net
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    volumes:
      - 'hapi-postgres:/var/lib/postgresql'


  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v6.1.0
    networks:
      - ddcc-net
    restart: always
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/hapi
      - spring.datasource.username=${POSTGRES_USER:-admin}
      - spring.datasource.password=${POSTGRES_PASSWORD:-admin}
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.max_page_size=50
      - hapi.fhir.default_page_size=20
    ports:
      - 8081:8080
    depends_on:
      - db
